services:
  moria:
    image: andrewsav/moria
    container_name: moria
    restart: unless-stopped
    stop_signal: SIGINT # This is for graceful termination, do not change it, unless you know what you are doing
    volumes:
      - './moria-server/server:/server'
      - './moria-server/steam:/root/Steam'
    ports:
      - '7777:7777/udp'
