services:
  se-server:
    image: devidian/spaceengineers:winestaging
    container_name: se-ds-docker
    restart: unless-stopped
    volumes:
      # left side: your docker-host machine
      # right side: the paths in the image (!!do not change!!)
      - /home/ubuntu/spaceengineers/server/plugins:/appdata/space-engineers/plugins
      - /home/ubuntu/spaceengineers/server/instances:/appdata/space-engineers/instances
      - /home/ubuntu/spaceengineers/server/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - /home/ubuntu/spaceengineers/server/steamcmd:/root/.steam
    ports:
      - target: 27016
        published: 27016
        protocol: udp
        mode: host
    environment:
      - WINEDEBUG=-all
      - INSTANCE_NAME=${server_name}
