services:
  satisfactory:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    build: .
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './satisfactory-server:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    restart: always
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G